name: Build and Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.18.0'
      - name: Install node packages
        run: yarn install
      - name: Set Git Credential
        run: git config user.name "Lempereur Corentin" && git config user.email "<73390812+aredli16@users.noreply.github.com>"
      - name: Deploy
        run: yarn run deploy